### ISSUE TITLE
Error to Add staticField 

### ISSUE THREAD

**Issue by woojuin** [osiegmar/logback-gelf#1] opened 2016-07-13 05:23 UTC
thanks for making good library osiegmar!!

i have issue to use staticField.
when i use staticField then
 
Logging system failed to initialize using configuration from 'classpath:logback.xml'
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.action.NestedBasicPropertyIA - Unexpected aggregationType AS_BASIC_PROPERTY_COLLECTION
ERROR in ch.qos.logback.core.joran.action.NestedBasicPropertyIA - Unexpected aggregationType AS_BASIC_PROPERTY_COLLECTION

but when i remove staticfiled or there is no value in staticfield , then execute normally...
please give me a advise 

<appender name="GELFTCP" class="de.siegmar.logbackgelf.GelfTcpAppender">
    <graylogHost>localhost</graylogHost>
    <graylogPort>12201</graylogPort>
    <layout class="de.siegmar.logbackgelf.GelfLayout">
      <originHost>woojuin</originHost>

      <shortPatternLayout class="ch.qos.logback.classic.PatternLayout">
        <pattern>%m%nopex</pattern>
      </shortPatternLayout>
      <fullPatternLayout class="ch.qos.logback.classic.PatternLayout">
        <pattern>%m</pattern>
      </fullPatternLayout>
      <staticField>os_name:win</staticField>
    </layout>
  </appender>

**Comment by osiegmar** [comment] 2016-07-13 05:56
Thanks for your feedback!

I think this is caused by a regression bug of logback 1.1.7 and should not affect earlier and later versions.

See http://jira.qos.ch/browse/LOGBACK-1158

Please let me know if downgrading or upgrading logback fixes your problem.

**Comment by osiegmar** [comment] 2016-07-14 05:47
Closing this issue as I think this is not a bug/problem within logback-gelf - let me know, if I'm wrong.

**Closed by osiegmar** 2016-07-14 05:47 UTC
Labels: help wanted

**Comment by zachofalltrades** [comment] 2017-01-26 19:58
I can confirm that I encountered this issue when using logback 1.1.7, and that the problem went away after updating to logback 1.1.9
