### ISSUE TITLE
inetaddress.getlocalhost().getcanonicalhostname() cause slow startup

### ISSUE THREAD

**Issue by chouex** [osiegmar/logback-gelf#43] opened 2020-01-07 10:03 UTC
after added de.siegmar.logbackgelf.GelfUdpAppender to logback-spring.xml the application will freeze 15s before spring logo appear, 
debug the constructor of GelfUdpAppender found getcanonicalhostname() is too slow to resolve
```
//host = nameService.getHostByAddr(addr.getAddress());   //15s to load
getHostFromNameService:618, InetAddress (java.net)
getCanonicalHostName:589, InetAddress (java.net)
buildHostname:279, GelfEncoder (de.siegmar.logbackgelf)
start:265, GelfEncoder (de.siegmar.logbackgelf)
```

**root cause maybe npcap in windows.**
reference: https://stackoverflow.com/questions/47031687/getcanonicalhostname-is-very-slow

add that ip to host file fix one computer, but i dont want to modify every developer's hosts file.

**could you use a faster way to get hostname without resolve?**
https://stackoverflow.com/questions/7348711/recommended-way-to-get-hostname-in-java

tried to override buildHostname() but it was private.

os: windows 10

**Comment by osiegmar** [comment] 2020-01-07 22:17
Thanks for the info!

I think, the freeze is caused by a DNS or local hosts misconfiguration. If the IP address cannot be resolved to a hostname via DNS or local hosts file, the timeout might occur. I do not plan to change the implementation, as it is already the most portable (and in my point of view correct) way to handle it.

But I created a way to allow a different configuration – check the [supplier branch](https://github.com/osiegmar/logback-gelf/tree/feature/supplier).

Please let me know, if this works for you.

**Comment by chouex** [comment] 2020-01-08 01:39
tested the new bench,  the new HostnameSupplier successfully resolve my custom hostname, thanks a lot. 

```
public class MyHostnameSupplier extends HostnameSupplier {
    @Override
    public String get() throws UnknownHostException {
        return InetAddress.getLocalHost().getHostName() ;
    }
}
```

**Comment by osiegmar** [comment] 2020-01-08 18:05
Thanks for your feedback! I merged the change (including a rename to HostnameProvider) to master in 36120e3bf928f2fec3461712269b330bbcb9e63c. As this work is still work-in-progress, I keep this ticket open...

**Comment by osiegmar** [comment] 2020-01-08 18:36
I'd like to try another, more consistent approach. I found the concept of [PropertyDefiner](http://logback.qos.ch/manual/configuration.html#definingPropsOnTheFly) in the logback documentation. That could be used to configure a custom 'HostnameProvider' in the current released version of logback-gelf:

```
<configuration>

    <define name="myHostname" class="your.HostnameProvider"/>

    <appender name="GELF" class="de.siegmar.logbackgelf.GelfUdpAppender">
        <graylogHost>localhost</graylogHost>
        <graylogPort>12201</graylogPort>
        <encoder class="de.siegmar.logbackgelf.GelfEncoder">
            <originHost>${myHostname}</originHost>
        </encoder>
    </appender>

    <root level="debug">
        <appender-ref ref="GELF" />
    </root>

</configuration>
```

Could you give it a spin?

**Comment by chouex** [comment] 2020-01-09 05:55
i prefer using PropertyDefiner, 
seems does the same thing as HostnameSupplier and dont need wait for next release.

```
public class MyHostnameSupplier extends PropertyDefinerBase {


    @Override
    public String getPropertyValue() {
        try {
            return InetAddress.getLocalHost().getHostName() +" - (custom)";
        } catch (UnknownHostException e) {
            e.printStackTrace();
        return "error";
        }
    }
}

```

**Comment by osiegmar** [comment] 2020-01-09 06:18
OK, thanks. Also note, that you could use the addError() method in your class to pass the exception to logback.

**Comment by chouex** [comment] 2020-01-09 06:43
I found the new GelfUdpChunker use different logic to resolve host (not using HostnameSupplier provided), although there is no issue for me.

if it does not matter, the issue could close.

**Closed** 2020-01-22 18:11 UTC
Labels: enhancement
